[[cases]]
name = "sample0"
stdin = """5 2
3 2
5 9
0 1
4 3
8 10
0 0
"""
answer = """43
"""

[[cases]]
name = "sample1"
stdin = """6 4
3 1
2 1
1 2
1 3
3 3
0 0
0 0
"""
answer = """17
"""

[[cases]]
name = "sample2"
stdin = """4 3
3 4
1 1
1 1
5 6
0 0
"""
answer = """17
"""

[[cases]]
name = "sample3"
stdin = """10 5
7 8
4 9
3 7
5 9
7 2
10 3
0 10
3 2
6 3
7 9
0 0
"""
answer = """102
"""
